USE [master]
GO

/****** Object:  Database [AECMIS]    Script Date: 04/26/2013 22:23:07 ******/
CREATE DATABASE [AECMIS] ON  PRIMARY 
( NAME = N'AECMIS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER02\MSSQL\DATA\AECMIS.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AECMIS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER02\MSSQL\DATA\AECMIS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AECMIS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AECMIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AECMIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AECMIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AECMIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AECMIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AECMIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [AECMIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AECMIS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AECMIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AECMIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AECMIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AECMIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AECMIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AECMIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AECMIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AECMIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AECMIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AECMIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AECMIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AECMIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AECMIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AECMIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AECMIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AECMIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AECMIS] SET  READ_WRITE 
GO

ALTER DATABASE [AECMIS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AECMIS] SET  MULTI_USER 
GO

ALTER DATABASE [AECMIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AECMIS] SET DB_CHAINING OFF 
GO


